### PR TITLE
CHANGED: Added Oracle and SQLserver database adapters

### PR DESCRIPTION
**Pull request by tarellel**
About a 14 months ago @delonnewman and I forked mini_sql and added Oracle and SQLserver database adapters. The [fork](https://github.com/delonnewman/mini_sql) is a bit out of date from the current primary branch. This is a PR that includes all of your latest changes, as well as an update to our code to include the Oracle and SQLserver database adapters.

I believe the only thing that's missing if adding Oracle and SQLserver tests to the github actions. But I'm not exactly sure how add the tests for these actions. I can tell you from first hand experience that we've been using in our production applications for the 14 months and it has made a massive performance improvement over using ActiveRecord with Oracle and SQLserver _(where these queries are used).

### CODE REVIEW

**Comment by SamSaffron** [comment]
This is certainly going to be a big challenge to test, is there a free way to install these locally? 

All of that said as long as you are happy to maintain this going forward the risk here seems extremely low.

Can you include something in the changlog here and readme as well to guide people? 

So happy to hear this has made your application so much faster!

**Comment by delonnewman** [comment]
I'd started looking into setting up a docker environment to test oracle and sql server locally a while back that seems like the that would be the most reasonable way forward. Unless there's now support for oracle and sql server with GitHub actions.

**Comment by SamSaffron** [comment]
Yeah I docker images sound fine for local testing even if this evades CI for now. (as long as CI is not failing)

**Comment by tarellel** [comment]
Sure thing, we've got a pretty heavy docker setup for our setup, and a ton of docker images in our internal pipeline.
The issue with adding the oracle/tiny_tds gems to the stack is you when setting up an ruby container to connect to Oracle you need to have the Oracle instant-client which has some distribution [licensing](https://www.oracle.com/downloads/licenses/instant-client-lic.html) issues.

In a recent rails generator gem I created, I added these databases and docker setup to account for if the application will use Oracle, Postgres, SQLserver, or MySQL, so I'm already part of the way there already.
- [Dockerfile](https://github.com/tarellel/kowl/blob/master/lib/kowl/templates/docker/Dockerfile.debian.tt#L62)
- [Oracle service in docker-compose](https://github.com/tarellel/kowl/blob/master/lib/kowl/docker.rb#L158)

Give me a few days and I'll see what I can come up with.

I'll also see about correcting the bundle install issues caused by adding tiny_tds to to the gemspec file.
This is caused because in order to connect to the databases you need 3rd party libraries that the adapter gems use to connect to the databases (ie: freetds and the oracle instant-client)

And thank you for your patient.

**Comment by SamSaffron** [comment]
I am uneasy sitting on this for too much longer, I wonder if we simply merge as is once conflicts are resolved, at least the code will be in the repo. 

As long as you are open to addressing questions / issues I am fine with it.

**Comment by tarellel** [comment]
I apologize for not resolving the issues with this PR sooner.
I have been dealing with some health issues, for the last year or so.

In the meantime, I want to rebase from the current master branch, resolve any issues, and address any concerns you may have.

**Comment by SamSaffron** [comment]
Oh no @tarellel, take care, so sorry to hear. Nothing is urgent here.

**Comment by delonnewman** [comment]
> I apologize for not resolving the issues with this PR sooner. I have been dealing with some health issues, for the last year or so.
> 
> In the meantime, I want to rebase from the current master branch, resolve any issues, and address any concerns you may have.

@tarellel If there's anything I can do to help please feel free to let me know.  I hope you and the family are well.

**Pull request closed without merging**
