### PR TITLE
encode param as pg array

### PR DESCRIPTION
**Pull request by ermolaev**

### CODE REVIEW

**Comment by SamSaffron** [comment]
Hmmm ... maybe we support: 

`conn.auto_encode_arrays!` 

Then you would not need `.array` calls if you are careful with your usage.

**Comment by ermolaev** [comment]
if we introduce `conn.auto_encode_arrays!` then it will be necessary to rewrite the old sql

with `conn.array` developers can create arrays only in the necessary places

```ruby
conn.query("select * from products where supplier_id = ? and category_ids && ?", 127, conn.array([12, 24, 67]))
```

`conn.array` need not only in `prepared` connection

**Comment by SamSaffron** [comment]
understood, my thinking is that `conn.auto_encode_arrays!` would be something you enable if you are just about to start a brand new project and saves you ceremony.

**Comment by SamSaffron** [comment]
Is there any downside to doing this 100% automatically, if we see an Array in the param we just use encode array? What can break with a change like that?

**Review by SamSaffron — APPROVED** [review]

**Pull request merged**
