### PR TITLE
allow multiple occurencies of builder statements

### PR DESCRIPTION
**Pull request by xronos-i-am**

### CODE REVIEW

**Comment by xronos-i-am** [comment]
reopen #42 because of loosing code in master branch

**Comment by ermolaev** [comment]
@SamSaffron 

now mini-sql behaves incorrectly

```ruby
MINI_SQL.build('(/*select*/ from orders) union (/*select*/ from line_items)').select('user_id').query
(SELECT user_id from orders) union (/*select*/ from line_items)
```

this PR fix it

```ruby
(SELECT user_id from orders) union (SELECT user_id from line_items)
```

**Comment by SamSaffron** [comment]
I support this, but it is technically a breaking change, going to have to bump versions for it.

**Comment by SamSaffron** [comment]
I wonder if we need a new param to explicitly opt for polymorphic.

**Comment by ermolaev** [comment]
@SamSaffron hello, I come across this problem from time to time in my work

also not work with `sql_literal`, this PR fix it

```ruby
builder = MINI_SQL.build(<<~SQL)
  SELECT
    DISTINCT ON (/*snap_grid*/)
    coords
  FROM delivery_offices
  ORDER BY /*snap_grid*/
SQL

builder.sql_literal(snap_grid: 'ST_SnapToGrid(coords, 0.0007, 0.00035)')
```

can you merge this PR and bump new gem version?

**Comment by SamSaffron** [comment]
Yes I am fine with this, but I would like an example added to the README as well here. It feels like a feature we should document. 

Also, technically this is a breaking change, we are going to need a full version bump for it, go ahead and do so and also explain in the changelog.

**Comment by xronos-i-am** [comment]
> Yes I am fine with this, but I would like an example added to the README as well here

Hello, @SamSaffron. It's done. Do you bump version and add comment to changelog by yourself?

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
I am merging it in, will discuss internally if it makes sense to do a full major version bump for this. 

Really depends how you squint, this is either a breaking change or bug fix...

**Pull request merged**
