### PR TITLE
Marshallable serializer

### PR DESCRIPTION
**Pull request by xronos-i-am**
The PR has 2 goals:
1) Simplify usage of serializer with Rails.cache
2) Speed up deserialization

To fetch cached MiniSql results we have to do something like this:

```ruby
  recent_topics_json =
    Rails.cache.fetch('recent-topics') do
      MiniSql::Serializer.to_json(DB.query('SELECT * FROM topics ORDER BY id DESC LIMIT 10'))
    end
  recent_topics = DB.from_json(recent_topics_json)
```

With the proposed changes we can able to simplify code:
```ruby
recent_topics =
  Rails.cache.fetch('recent-topics') do
    MiniSql::Serializer.marshallable(DB.query('SELECT * FROM topics ORDER BY id DESC LIMIT 10'))
  end
```

### CODE REVIEW

**Comment by xronos-i-am** [comment]
In the following bench you can see that performance of `to_json`/`from_json` stays the same. `marshal_dump` is expected to be slower than `to_json`, but deserializing `i/s` is same too.

```ruby
require 'benchmark/ips'
require 'mini_sql'
require 'json'

class MarshalSerializer < Array
  MAX_CACHE_SIZE = 500

  def initialize(result)
    replace(result)
  end

  def self.to_json(result)
    wrapper =
      if result.length == 0
        {}
      else
        {
          "decorator" => result[0].class.decorator.to_s,
          "fields" => result[0].to_h.keys,
          "data" => result.map(&:values),
        }
      end

    JSON.generate(wrapper)
  end

  def self.from_json(json)
    wrapper = JSON.parse(json)
    if !wrapper["data"]
      []
    else
      materializer = cached_materializer(wrapper['fields'], wrapper['decorator'])
      wrapper["data"].map do |row|
        materializer.materialize(row)
      end
    end
  end

  def self.marshal_dump(result)
    new(result)
  end

  private

  def _dump(level)
    self.class.serialize do
      if size == 0
        {}
      else
        {
          "decorator" => first.class.decorator.to_s,
          "fields" => first.to_h.keys,
          "data" => map(&:values),
        }
      end
    end
  end

  def self.serialize
    Marshal.dump(yield)
  end

  def self.deserialize
    Marshal.load(yield)
  end

  def self._load(dump)
    wrapper = deserialize { dump }
    materializer = cached_materializer(wrapper['fields'], wrapper['decorator'])
    result = self.new(wrapper['data'])
    result.map! { |row| materializer.materialize(row) }
    result
  end

  def self.cached_materializer(fields, decorator_module = nil)
    @cache ||= {}
    key = fields
    m = @cache.delete(key)
    if m
      @cache[key] = m
    else
      m = @cache[key] = materializer(fields)
      @cache.shift if @cache.length > MAX_CACHE_SIZE
    end

    if decorator_module && decorator_module.length > 0
      decorator = Kernel.const_get(decorator_module)
      m = m.decorated(decorator)
    end

    m
  end

  def self.materializer(fields)
    Class.new do
      extend MiniSql::Decoratable
      include MiniSql::Result

      attr_accessor(*fields)

      instance_eval <<~RUBY
        def materialize(values)
          r = self.new
          #{col = -1; fields.map { |f| "r.#{f} = values[#{col += 1}]" }.join("; ")}
          r
        end
      RUBY
    end
  end
end

PgResult =
  Struct.new(:rows) do
    def ntuples
      rows.size
    end

    def fields
      @fields ||= rows[0].keys
    end

    def getvalue(row_num, col_num)
      rows[row_num][fields[col_num]]
    end
  end

module TopicDecorator
  def permalink
    "#{id}-#{title}"
  end
end

topics =
  10.times.map do |i|
    id = rand(1..9999)
    {
      id: id,
      title: "topic #{id}",
    }
  end
result = PgResult.new(topics)

materialized = MiniSql::Postgres::Connection.default_deserializer_cache.materialize(result, TopicDecorator)

Benchmark.ips do |r|
  r.report("module to_json") do
    MiniSql::Serializer.to_json(materialized)
  end
  r.report("class to_json") do
    MarshalSerializer.to_json(materialized)
  end
  r.compare!
end

# Warming up --------------------------------------
#       module to_json     6.999k i/100ms
#        class to_json     6.967k i/100ms
# Calculating -------------------------------------
#       module to_json     69.549k (± 2.4%) i/s -    349.950k in   5.034501s
#        class to_json     71.720k (± 2.6%) i/s -    362.284k in   5.054871s

# Comparison:
#        class to_json:    71719.8 i/s
#       module to_json:    69549.4 i/s - same-ish: difference falls within error

Benchmark.ips do |r|
  r.report("to_json") do
    Marshal.dump(MiniSql::Serializer.to_json(materialized))
  end
  r.report("marshal") do
    Marshal.dump(MarshalSerializer.marshal_dump(materialized))
  end
  r.compare!
end

# Warming up --------------------------------------
#              to_json     5.623k i/100ms
#              marshal     4.326k i/100ms
# Calculating -------------------------------------
#              to_json     60.797k (± 3.7%) i/s -    303.642k in   5.001387s
#              marshal     41.654k (± 3.2%) i/s -    211.974k in   5.094239s

# Comparison:
#              to_json:    60797.3 i/s
#              marshal:    41653.9 i/s - 1.46x  (± 0.00) slower

json = Marshal.dump(MiniSql::Serializer.to_json(materialized))
marshal = Marshal.dump(MarshalSerializer.marshal_dump(materialized))

Benchmark.ips do |r|
  r.report("module from_json") do
    MiniSql::Serializer.to_json(materialized)
  end
  r.report("class from_json") do
    MarshalSerializer.to_json(materialized)
  end
  r.compare!
end

# Warming up --------------------------------------
#     module from_json     6.118k i/100ms
#      class from_json     6.814k i/100ms
# Calculating -------------------------------------
#     module from_json     66.584k (± 2.4%) i/s -    336.490k in   5.056535s
#      class from_json     66.404k (± 2.1%) i/s -    333.886k in   5.030304s

# Comparison:
#     module from_json:    66583.6 i/s
#      class from_json:    66403.8 i/s - same-ish: difference falls within error

Benchmark.ips do |r|
  r.report("from_json") do
    MiniSql::Serializer.from_json(Marshal.load(json))
  end
  r.report("marshal") do
    Marshal.load(marshal)
  end
  r.compare!
end

# Warming up --------------------------------------
#            from_json     5.270k i/100ms
#              marshal     5.387k i/100ms
# Calculating -------------------------------------
#            from_json     51.625k (± 2.7%) i/s -    258.230k in   5.005840s
#              marshal     53.534k (± 2.7%) i/s -    269.350k in   5.035220s

# Comparison:
#              marshal:    53533.6 i/s
#            from_json:    51625.0 i/s - same-ish: difference falls within error
```

**Comment by xronos-i-am** [comment]
Comparsion `JSON.parse`/`MessagePack.unpack`/`Oj.load`/`Marshal.load`:
```ruby
require 'benchmark/ips'
require 'mini_sql'
require 'json'
require 'oj'
require 'msgpack'

topics =
  10.times.map do |i|
    id = rand(1..9999)
    {
      'id' => id,
      'title' => "topic #{id}",
    }
  end
wrapper = { 'fields' => topics[0].keys, 'data' => topics.map(&:values) }

Benchmark.ips do |r|
  r.report("JSON.generate") do
    JSON.generate(wrapper)
  end
  r.report("Marshal.dump") do
    Marshal.dump(wrapper)
  end
  r.report("Oj.dump") do
    Oj.dump(wrapper)
  end
  r.report("MessagePack.pack") do
    MessagePack.pack(wrapper)
  end
  r.compare!
end

# Warming up --------------------------------------
#        JSON.generate    24.575k i/100ms
#         Marshal.dump     8.692k i/100ms
#              Oj.dump    51.041k i/100ms
#     MessagePack.pack    54.901k i/100ms
# Calculating -------------------------------------
#        JSON.generate    252.404k (± 3.4%) i/s -      1.278M in   5.068934s
#         Marshal.dump     93.956k (± 3.1%) i/s -    478.060k in   5.093095s
#              Oj.dump    523.021k (± 2.8%) i/s -      2.654M in   5.078542s
#     MessagePack.pack    537.523k (± 3.1%) i/s -      2.690M in   5.009864s

# Comparison:
#     MessagePack.pack:   537523.0 i/s
#              Oj.dump:   523021.5 i/s - same-ish: difference falls within error
#        JSON.generate:   252403.6 i/s - 2.13x  (± 0.00) slower
#         Marshal.dump:    93955.9 i/s - 5.72x  (± 0.00) slower

json = JSON.generate(wrapper)
marshal = Marshal.dump(wrapper)
oj = Oj.dump(wrapper)
msgpack = MessagePack.pack(wrapper)

Benchmark.ips do |r|
  r.report("JSON.parse") do
    JSON.parse(json)
  end
  r.report("Marshal.load") do
    Marshal.load(marshal)
  end
  r.report("Oj.load") do
    Oj.load(oj)
  end
  r.report("MessagePack.unpack") do
    MessagePack.unpack(msgpack)
  end
  r.compare!
end

# Warming up --------------------------------------
#           JSON.parse    13.004k i/100ms
#         Marshal.load    14.931k i/100ms
#              Oj.load    19.159k i/100ms
#   MessagePack.unpack    22.510k i/100ms
# Calculating -------------------------------------
#           JSON.parse    130.855k (± 3.3%) i/s -    663.204k in   5.073899s
#         Marshal.load    155.852k (± 3.5%) i/s -    791.343k in   5.083875s
#              Oj.load    205.019k (± 3.4%) i/s -      1.035M in   5.052433s
#   MessagePack.unpack    231.017k (± 3.8%) i/s -      1.171M in   5.074704s

# Comparison:
#   MessagePack.unpack:   231016.8 i/s
#              Oj.load:   205019.1 i/s - 1.13x  (± 0.00) slower
#         Marshal.load:   155852.1 i/s - 1.48x  (± 0.00) slower
#           JSON.parse:   130854.8 i/s - 1.77x  (± 0.00) slower
```

**Comment by xronos-i-am** [comment]
Overloadable interface `serialize`/`deserialize` allows us to use `MessagePack` instead of standard marshalling and achieve performance increase:

```ruby
class MessagePackSerializer < MiniSql::Serializer
  def self.serialize
    MessagePack.pack(yield)
  end

  def self.deserialize
    MessagePack.unpack(yield)
  end
end

class OjSerializer < MiniSql::Serializer
  def self.serialize
    Oj.dump(yield)
  end

  def self.deserialize
    Oj.load(yield)
  end
end

materialized = MiniSql::Postgres::Connection.default_deserializer_cache.materialize(result, TopicDecorator)

Benchmark.ips do |r|
  r.report("to_json") do
    Marshal.dump(MiniSql::Serializer.to_json(materialized))
  end
  r.report("marshal") do
    Marshal.dump(MiniSql::Serializer.marshal_dump(materialized))
  end
  r.report("msgpack") do
    Marshal.dump(MessagePackSerializer.marshal_dump(materialized))
  end
  r.report("oj") do
    Marshal.dump(OjSerializer.marshal_dump(materialized))
  end
  r.compare!
end

# Warming up --------------------------------------
#              to_json     1.376k i/100ms
#              marshal   793.000  i/100ms
#              msgpack     1.647k i/100ms
#                   oj     1.460k i/100ms
# Calculating -------------------------------------
#              to_json     13.908k (± 3.6%) i/s -     70.176k in   5.052625s
#              marshal      7.581k (± 1.7%) i/s -     38.064k in   5.022560s
#              msgpack     15.528k (± 1.7%) i/s -     79.056k in   5.092515s
#                   oj     13.983k (± 1.6%) i/s -     70.080k in   5.013079s

# Comparison:
#              msgpack:    15528.5 i/s
#                   oj:    13982.9 i/s - 1.11x  (± 0.00) slower
#              to_json:    13907.9 i/s - 1.12x  (± 0.00) slower
#              marshal:     7580.8 i/s - 2.05x  (± 0.00) slower

json = Marshal.dump(MiniSql::Serializer.to_json(materialized))
marshal = Marshal.dump(MiniSql::Serializer.marshal_dump(materialized))
msgpack = Marshal.dump(MessagePackSerializer.marshal_dump(materialized))
oj = Marshal.dump(OjSerializer.marshal_dump(materialized))

Benchmark.ips do |r|
  r.report("from_json") do
    MiniSql::Serializer.from_json(Marshal.load(json))
  end
  r.report("marshal") do
    Marshal.load(marshal)
  end
  r.report("msgpack") do
    Marshal.load(msgpack)
  end
  r.report("oj") do
    Marshal.load(oj)
  end
  r.compare!
end

# Warming up --------------------------------------
#            from_json     1.170k i/100ms
#              marshal     1.267k i/100ms
#              msgpack     1.701k i/100ms
#                   oj     1.423k i/100ms
# Calculating -------------------------------------
#            from_json     11.804k (± 2.0%) i/s -     59.670k in   5.057207s
#              marshal     12.523k (± 1.9%) i/s -     63.350k in   5.060283s
#              msgpack     16.564k (± 2.1%) i/s -     83.349k in   5.034364s
#                   oj     14.021k (± 2.7%) i/s -     71.150k in   5.078133s

# Comparison:
#              msgpack:    16563.5 i/s
#                   oj:    14021.3 i/s - 1.18x  (± 0.00) slower
#              marshal:    12523.4 i/s - 1.32x  (± 0.00) slower
#            from_json:    11803.7 i/s - 1.40x  (± 0.00) slower
```

**Comment by xronos-i-am** [comment]
@SamSaffron can you take a look please

**Comment by eviltrout** [comment]
Sam is unfortunately not around right now so this might have to wait a couple weeks, sorry.

**Comment by xronos-i-am** [comment]
ok, sure

**Comment by SamSaffron** [comment]
I worry about having a deep dependency on marshal, this automatically poisons cache on major ruby upgrades, it is not all win.

Can we make this an optional behavior?

**Comment by ermolaev** [comment]
I think that `_load` `_dump` has low dependency on marshal, because in this case marshaling a simple string
Are you aware of ruby versions that break Marshal's algorithm compatibility?

**Comment by ermolaev** [comment]
I think that `_load` `_dump` has low dependency on marshal, because in this case marshaling a simple string

```ruby
class A
  def initialize(b)
     @b = [b, b+2, {b: b+3}]
     @c = 'str'
  end
end

class AA
  def initialize(b)
    @b = [b, b+2, {b: b+3}]
    @c = 'str'
  end

  def _dump(level)
    JSON.generate(b: @b, c: @c)
  end
end


puts Marshal.dump(A.new(2000)) # o:A:@bi�i�{:bi�:@cIstr:ET
puts Marshal.dump(AA.new(2000)) # Iu:AA+{"b":[2000,2002,{"b":2003}],"c":"str"}:ET
```

Are you aware of ruby versions that break Marshal's algorithm compatibility?

**Comment by xronos-i-am** [comment]
> Can we make this an optional behavior?

No problem, but there is a problem with JSON serializing. Dates or custom types can not be automatically restored from JSON dump:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile do
  gem 'mini_sql', github: 'discourse/mini_sql'
end

require 'mini_sql'
require 'json'

PgResult =
  Struct.new(:rows) do
    def ntuples
      rows.size
    end

    def fields
      @fields ||= rows[0].keys
    end

    def getvalue(row_num, col_num)
      rows[row_num][fields[col_num]]
    end
  end

result = PgResult.new([{id: 1, date: Date.today}])

materialized = MiniSql::Postgres::Connection.default_deserializer_cache.materialize(result)
p materialized
# [#<#<Class:0x00007f0eabd4b370>:0x00007f0eabd4aa38 @id=1, @date=#<Date: 2021-02-01 ((2459247j,0s,0n),+0s,2299161j)>>]

json = MiniSql::Serializer.to_json(materialized)
puts json
# {"decorator":"","fields":["id","date"],"data":[[1,"2021-02-01"]]}

deserialized = MiniSql::Serializer.from_json(json)
p deserialized
# [#<#<Class:0x00007f0eabd49f48>:0x00007f0eabd496d8 @id=1, @date="2021-02-01">]
```

**Comment by SamSaffron** [comment]
Yeah that is a problem, I guess we just eat it up and use Marshal, will
have think about this and get something merged in.

**Comment by SamSaffron** [comment]
OK lets try this then ... weird error on 2.6, seems unrelated.

**Pull request merged**
